Finished CLI Gym App
RYelzhan/GymSpringCore pull request #1
Opened 2024-09-01 10:31 UTC by RYelzhan

Fully finished Project with tests.

2024-09-03 08:54 UTC, Atabek04 requested changes
Great job 👏 on implementing the core features! The codebase is generally clean and well-organized, but there are a few improvements needed to enhance its readability, maintainability, and security:

- [ ] **Use Optional for Null Checks**: Refactor methods to utilize Optional for handling potential null values, which will improve code readability and reduce the risk of NullPointerExceptions.
- [ ] **Implement Design Patterns**: Apply a _Factory Pattern_ for object creation (e.g., Trainee, Trainer) to encapsulate creation logic and improve maintainability.
- [ ] **Improve Test Coverage with Parameterized Tests:** Introduce parameterized tests to increase test coverage and efficiently validate multiple input scenarios.
- [ ] **Avoid Logging Sensitive Information**: Ensure that sensitive data (e.g., passwords) is not logged to comply with security best practices.
- [ ] **Refactor Long Methods for Readability**: Break down lengthy methods (such as run in GymFacade) into smaller, single-responsibility methods to follow clean code principles.
- [ ] **Optimize DAO Operations**: Create a generic DAO interface to reduce redundancy and promote code reuse across the data access layer.

Please address these items in your next commit to further improve the quality and security of the codebase.

2024-09-03 08:54 UTC, Atabek04 commented on src/main/java/com/epam/wca/gym/repository/database/InMemoryDatabase.java
> +    }
```suggestion
```

2024-09-03 08:54 UTC, Atabek04 commented on src/main/java/com/epam/wca/gym/service/impl/ProfileServiceImpl.java
> +public class ProfileServiceImpl implements ProfileService {
add @Getter annotation here also, in order to remove boilerplate code

2024-09-03 08:54 UTC, Atabek04 commented on src/main/java/com/epam/wca/gym/service/impl/ProfileServiceImpl.java
> +    private Map<String, Integer> usernameCounter;
Use of field injection is not recommended. Use constructor injection to promote immutability and make dependencies more visible.
```suggestion
    private Map<String, Integer> usernameCounter;
    
    @Autowired
  public TraineeServiceImpl(TraineeDAO traineeDAO) {
      this.traineeDAO = traineeDAO;
  }
```

2024-09-03 08:54 UTC, Atabek04 commented on src/main/java/com/epam/wca/gym/service/impl/TrainingServiceImpl.java
> +        }
**Use of Optional instead of Null Checks**
For example:
```java
Optional.ofNullable(traineeService.findById(trainingDTO.traineeId()))
        .orElseThrow(() -> new IllegalStateException("Trainee not found"));
```

2024-09-03 08:54 UTC, Atabek04 commented on src/main/java/com/epam/wca/gym/service/impl/TraineeServiceImpl.java
Consider implementing a Factory Pattern for creating instances like Trainee and Trainer.
Create a new file: UserFactory.java:
```java
public class UserFactory {
    public static Trainee createTrainee(TraineeDTO traineeDTO) {
        return new Trainee(traineeDTO.getFirstName(), traineeDTO.getLastName(), traineeDTO.getDateOfBirth(), traineeDTO.getAddress());
    }

    public static Trainer createTrainer(TrainerDTO trainerDTO) {
        return new Trainer(trainerDTO.getFirstName(), trainerDTO.getLastName(), trainerDTO.getTrainingType());
    }
}
```
Encapsulates the object creation logic, making the service classes cleaner and easier to maintain.

2024-09-03 08:54 UTC, Atabek04 commented on src/test/java/com/epam/wca/gym/service/ProfileServiceImplTest.java
> +        String expectedUsername = "John.Doe";
Use parameterized tests where possible to test multiple scenarios in a single test case.
```suggestion
@ParameterizedTest
@CsvSource({ "John, Doe, John.Doe", "Jane, Smith, Jane.Smith" })
void testCreateUserName(String firstName, String lastName, String expectedUsername) {
    assertEquals(expectedUsername, profileService.createUserName(firstName, lastName));
}
```

2024-09-03 08:54 UTC, Atabek04 commented on src/main/java/com/epam/wca/gym/facade/GymFacade.java
> +                System.out.println("Password: " + newTrainee.getPassword());
Never log sensitive data such as passwords. Ensure logs do not contain any user-identifiable information.
```java
log.info("User authenticated: {}", username);
```

2024-09-03 08:54 UTC, Atabek04 commented on src/main/java/com/epam/wca/gym/entity/Trainee.java
> +    private static ProfileService profileService;
**Avoid Using Static Dependencies in Instance Methods**
- Static dependencies like ProfileService in the Trainee and Trainer classes can create tight coupling and make testing difficult.
- Inject dependencies through constructors or setters.
```suggestion
    public Trainee(ProfileService profileService, ...) {
        this.profileService = profileService;
        // Other initializations
    }
```

2024-09-03 08:54 UTC, Atabek04 commented on src/main/java/com/epam/wca/gym/facade/GymFacade.java
**Refactor Long Methods for Readability**
- Some methods, like `register` and `run` in GymFacade, are lengthy and have multiple responsibilities, making them harder to read and maintain.
- Break down long methods into smaller, single-responsibility methods.
- This approach adheres to the _Single Responsibility_ Principle (SRP) and improves maintainability.

2024-09-03 08:54 UTC, Atabek04 commented on src/main/java/com/epam/wca/gym/repository/TraineeDAO.java
**Optimize Data Access Layer (DAO) Operations**
- Operations like `find`, `save`, `update`, and `delete` are scattered and sometimes redundant.
- Use a generic DAO interface or utility class to reduce redundancy and make the code _DRY (Don’t Repeat Yourself)._
```java
public interface GenericDAO<T, ID> {
    T save(T entity);
    void delete(ID id);
    T findById(ID id);
}
```

2024-09-03 08:54 UTC, Atabek04 commented on src/main/java/com/epam/wca/gym/service/impl/ProfileServiceImpl.java
> +        return password.toString();
**Improve Security by Hashing Passwords**
I'm sure you know this, just reminder for future projects
- Hash passwords using a strong algorithm (e.g., BCrypt) before storing them.
```suggestion
        return BCrypt.hashpw(password.toString() , BCrypt.gensalt());
```

2024-09-03 12:03 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/entity/Trainee.java
> +    private static ProfileService profileService;
I will consider it

2024-09-03 13:22 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/repository/TraineeDAO.java
Done

2024-09-03 13:27 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/repository/database/DatabaseInitializationPostProcessor.java
> +                                Map<String, Integer> usernameStorage, Map<String, Long> userToIdStorage) throws ParseException {
Parsing does throw exception.

2024-09-03 13:28 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/repository/database/InMemoryDatabase.java
> +public class InMemoryDatabase {
Done

2024-09-03 13:32 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/service/impl/ProfileServiceImpl.java
> +    private Map<String, Integer> usernameCounter;
It was written in document to use @Autowired  fo dependency injection into services

2024-09-03 13:33 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/service/impl/ProfileServiceImpl.java
> +        return password.toString();
I will consider it

2024-09-03 13:34 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/service/impl/ProfileServiceImpl.java
> +public class ProfileServiceImpl implements ProfileService {
Done

2024-09-03 15:57 UTC, RYelzhan commented on src/test/java/com/epam/wca/gym/service/ProfileServiceImplTest.java
> +        String expectedUsername = "John.Doe";
Done

2024-09-03 15:57 UTC, RYelzhan commented on src/test/java/com/epam/wca/gym/service/ProfileServiceImplTest.java
> +        MockitoAnnotations.openMocks(this);
Done

2024-09-03 16:00 UTC, RYelzhan commented on src/test/java/com/epam/wca/gym/service/TraineeServiceImplTest.java
> +import static org.mockito.ArgumentMatchers.any;
It is used: @Test
    void testCreateTrainee() {
        when(traineeDAO.save(any(Trainee.class))).thenReturn(trainee);
        ...                                    ^
}

2024-09-03 16:59 UTC, Atabek04 approved these changes
LGTM!

2024-09-04 13:19 UTC, maximelyashevich approved these changes
Good job! Reviewed from my side. Please check out my comments to improve code quality.

Regards,
Maks

2024-09-04 13:19 UTC, maximelyashevich commented on src/main/java/com/epam/wca/gym/repository/database/InMemoryDatabase.java
> +*/
Let's follow the `YAGNI` principle :)
```suggestion
```

2024-09-04 13:19 UTC, maximelyashevich commented on src/main/java/com/epam/wca/gym/utils/AppConstants.java
> +    }
Can we consider a `@UtilityClass` from Lombok? See https://projectlombok.org/features/experimental/UtilityClass for more details.

2024-09-05 16:14 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/app/GymApplication.java
> +import org.springframework.context.annotation.AnnotationConfigApplicationContext;
Done

2024-09-05 16:16 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/entity/Trainee.java
> +public class Trainee extends User{
Done

2024-09-05 18:20 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/entity/Trainee.java
> +    private Date dateOfBirth;
Needed refactoring in a lot places, but done

2024-09-05 19:09 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/entity/TrainingType.java
> +    ORDINARY, POWERLIFTING, CALISTHENICS, CROSSFIT, YOGA, PILATES
Done

2024-09-05 19:10 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/entity/User.java
> +    }
Yeah, deleted it

2024-09-05 19:10 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/facade/GymFacade.java
Done

2024-09-05 19:10 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/facade/GymFacade.java
> +import com.epam.wca.gym.entity.*;
Done

2024-09-05 19:11 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/facade/GymFacade.java
> +@Component
Done

2024-09-05 19:12 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/facade/GymFacade.java
> +                }
Done

2024-09-05 19:13 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/facade/GymFacade.java
> +        System.out.println("q - quit");
Got it

2024-09-05 19:34 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/service/impl/TrainingServiceImpl.java
> +        }
Done

2024-09-05 19:34 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/utils/AppConstants.java
> +    }
Done

2024-09-05 19:45 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/facade/GymFacade.java
> +    }
Done

2024-09-05 19:54 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/entity/Trainee.java
> +    }
Next time, will consider, thanks

2024-09-05 21:35 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/facade/GymFacade.java
> +public class GymFacade {
Done

2024-09-05 21:35 UTC, RYelzhan commented on src/main/java/com/epam/wca/gym/facade/GymFacade.java
> +        if (trainee != null && trainee.getPassword().equals(password) ||
Done

2024-09-07 10:20 UTC, merged